### ISSUE TITLE
Add Radio Group

### ISSUE THREAD

**Issue by Seehed** [zcraber/powered-by-azuracast#192]
**Name of the Radio Station**
Provide the complete name of the radio station including FM/AM frequency (if any).

1. Olix Radio (Malaysia)
   - https://s2.joeycast.com/listen/typicalmedia/olix1.mp3
2. Olix Chills (Malaysia)
   - https://s2.joeycast.com/listen/typicalmedia/olix2.mp3
3. Gan Network (Malaysia)
   - https://s2.joeycast.com/listen/typicalmedia/hits247.mp3
4. Gan Asia (Malaysia)
   - https://s2.joeycast.com/listen/typicalmedia/ganasia.mp3
5. Gan Chills (Malaysia)
   - https://s2.joeycast.com/listen/typicalmedia/ganchills.mp3
6. Glitch FM (UK)
   - https://s2.joeycast.com/listen/typicalmedia/glitchfm.mp3
7. Hits247 (USA)
   - https://s2.joeycast.com/listen/typicalmedia/hits247.mp3
8. Dance247 (USA)
   - https://s2.joeycast.com/listen/typicalmedia/dance247.mp3
9. Viral FM (USA)
   - https://s2.joeycast.com/listen/typicalmedia/viralfm.mp3
10. RMF FM (USA)
    - https://s2.joeycast.com/listen/typicalmedia/rmfrblx.mp3
11. Foreverworld FM (USA)
    - https://s2.joeycast.com/listen/typicalmedia/foreverworldfm.mp3
12. Ono Radio (USA)
    - https://s2.joeycast.com/listen/typicalmedia/onoradio.mp3
13. Rika Radio (Malaysia)
    - https://s2.joeycast.com/listen/typicalmedia/rikaradio.mp3

**URL**
https://typicalmedia,net - U should be able to find all the URLs of the stations that do have websites.

**Comment by zcraber** [comment]
@Seehed Thanks for the suggestions. Could you please add the websites of each station instead of stream URLs?

**Comment by Seehed** [comment]
https://hits247.live
https://viralfm.net
https://dance.hits247.live
https://foreverworldlive.com
https://robloxmusicfest.us.to (RMF FM)
https://giorgioworldmedia.wixsite.com/website/ (GWM FM)
https://thegan.typicalmedia.net (owns all Gan * , Olix, Rika radio stations)
https://glitchfm.typicalmedia.net (Glitch FM)
All of these stations are owned by me.

**Comment by zcraber** [comment]
I checked it, unable to play the radio through the first four websites. Shows an error: `Error Attribute "station" is required and is empty in this request src/Http/ServerRequest.php : L156`

**Comment by zcraber** [comment]
I've added the working stations. Feel free to comment when the rest are live.
